# Generated by Django 3.1.5 on 2021-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='icon_code',
            field=models.CharField(default='Icon', max_length=50),
            preserve_default=False,
        ),
    ]
