# Generated by Django 3.1.5 on 2021-01-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_counter_icon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='icon_code',
        ),
    ]
