# Generated by Django 3.1.5 on 2021-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
