# Generated by Django 3.1.5 on 2021-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_slider_title_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_space_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_space_top',
            field=models.IntegerField(default=0),
        ),
    ]
